# Generated by Django 4.1.3 on 2022-11-21 13:23

from django.db import migrations, models
import scholar_system.seminars.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=35)),
                ('date', models.DateField(validators=[scholar_system.seminars.validators.validate_future_date])),
                ('time', models.TimeField()),
                ('link', models.URLField()),
            ],
        ),
    ]
