# Generated by Django 4.1.3 on 2022-11-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='theme',
            field=models.CharField(max_length=100),
        ),
    ]
