# Generated by Django 4.1.3 on 2022-11-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0002_alter_seminar_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminar',
            options={'ordering': ['date']},
        ),
    ]
