# Generated by Django 4.1.3 on 2022-12-15 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0004_alter_seminar_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='link',
            field=models.URLField(validators=[django.core.validators.URLValidator]),
        ),
    ]
