# Generated by Django 4.1.3 on 2022-11-15 13:38

from django.db import migrations
import scholar_system.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='masteruser',
            managers=[
                ('objects', scholar_system.accounts.models.Director()),
            ],
        ),
    ]
