# Generated by Django 4.1.3 on 2022-11-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_masteruser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masteruser',
            name='phone_no',
        ),
    ]
