# Generated by Django 4.1.3 on 2022-11-30 13:23

import django.core.validators
from django.db import migrations, models
import scholar_system.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_masteruser_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteruser',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='first_name',
            field=models.CharField(max_length=15, validators=[scholar_system.accounts.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='last_name',
            field=models.CharField(max_length=15, validators=[scholar_system.accounts.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='username',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(4), scholar_system.accounts.validators.validate_username]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=15, validators=[scholar_system.accounts.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=15, validators=[scholar_system.accounts.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default=False, max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(4), scholar_system.accounts.validators.validate_username]),
        ),
    ]
