# Generated by Django 4.1.3 on 2022-12-13 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_masteruser_age_alter_masteruser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteruser',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(14)]),
        ),
    ]
