# Generated by Django 4.1.3 on 2022-11-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_paper_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-publication_date']},
        ),
    ]
